name: Nix Flake Validation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Only run if nix files, the lockfile, or secrets change
    paths:
      - "**.nix"
      - "flake.lock"
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
    # Only run if nix files, the lockfile, or secrets change
    paths:
      - "**.nix"
      - "flake.lock"
      - "**.yml"
      - "**.yaml"
jobs:
  validate:
    name: Validate (${{ matrix.system }})
    runs-on: nix-container-builder-${{ matrix.system }}
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
    steps:
      - name: Checkout Code
        uses: https://code.forgejo.org/actions/checkout@v7
      - name: Run Prereqs
        uses: ./.forgejo/workflows-composite/setup-nix
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
      - name: Verify Flake Metadata
        run: nix build github:srid/devour-flake --dry-run -L --no-link --print-out-paths --override-input flake ./
